"""Change current job to designation.

Revision ID: b955c27a10b3
Revises: 4f25d1428172
Create Date: 2023-05-08 18:05:50.570965

"""
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b955c27a10b3"
down_revision = "4f25d1428172"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "designation",
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "date_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uid",
            sqlmodel.sql.sqltypes.GUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("created_by", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("modified_by", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(op.f("ix_designation_title"), "designation", ["title"], unique=True)
    op.create_index(op.f("ix_designation_uid"), "designation", ["uid"], unique=True)
    op.drop_index("ix_current_job_title", table_name="current_job")
    op.drop_index("ix_current_job_uid", table_name="current_job")
    op.drop_constraint(
        "fk_employee_current_job_uid_current_job", "employee", type_="foreignkey"
    )
    op.drop_table("current_job")
    op.add_column(
        "employee",
        sa.Column("designation_uid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
    )
    op.create_foreign_key(None, "employee", "designation", ["designation_uid"], ["uid"])
    op.drop_column("employee", "current_job_uid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee",
        sa.Column(
            "current_job_uid", postgresql.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "employee", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "fk_employee_current_job_uid_current_job",
        "employee",
        "current_job",
        ["current_job_uid"],
        ["uid"],
    )
    op.drop_column("employee", "designation_uid")
    op.create_table(
        "current_job",
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "date_created",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "date_modified",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "uid",
            postgresql.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "modified_by", postgresql.UUID(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("uid", name="pk_current_job"),
    )
    op.create_index("ix_current_job_uid", "current_job", ["uid"], unique=False)
    op.create_index("ix_current_job_title", "current_job", ["title"], unique=False)
    op.drop_index(op.f("ix_designation_uid"), table_name="designation")
    op.drop_index(op.f("ix_designation_title"), table_name="designation")
    op.drop_table("designation")
    # ### end Alembic commands ###
