"""drop badge_number and termination_date.

Revision ID: f51f411a1f4a
Revises: 38b4e3ee8414
Create Date: 2023-05-13 18:33:39.444703

"""
import sqlalchemy as sa

from alembic import op

pass


# revision identifiers, used by Alembic.
revision = "f51f411a1f4a"
down_revision = "38b4e3ee8414"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_employee_badge_number", table_name="employee")
    op.drop_column("employee", "current_termination_date")
    op.drop_column("employee", "badge_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee",
        sa.Column("badge_number", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "employee",
        sa.Column(
            "current_termination_date", sa.DATE(), autoincrement=False, nullable=True
        ),
    )
    op.create_index(
        "ix_employee_badge_number", "employee", ["badge_number"], unique=False
    )
    # ### end Alembic commands ###
