"""add level_order column to educational_level.

Revision ID: 7d515c4e56aa
Revises: 91341154b6f6
Create Date: 2023-05-18 16:03:11.451837

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7d515c4e56aa"
down_revision = "91341154b6f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "educational_level", sa.Column("level_order", sa.Integer(), nullable=False)
    )
    op.create_unique_constraint(None, "educational_level", ["level_order"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "educational_level", type_="unique")  # type: ignore
    op.drop_column("educational_level", "level_order")
    # ### end Alembic commands ###
