"""add is_terminated column to employee table.

Revision ID: a52ad50c16c2
Revises: 7d515c4e56aa
Create Date: 2023-05-25 21:45:48.327061

"""
import sqlalchemy as sa

from alembic import op

pass


# revision identifiers, used by Alembic.
revision = "a52ad50c16c2"
down_revision = "7d515c4e56aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employee", sa.Column("is_terminated", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee", "is_terminated")
    # ### end Alembic commands ###
