"""add columns to employee table.

Revision ID: 63b433c7a929
Revises: eaf5624377ff
Create Date: 2023-06-03 15:50:38.637639

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "63b433c7a929"
down_revision = "eaf5624377ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Uprade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee",
        sa.Column(
            "origin_of_birth",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
    )
    op.add_column(
        "employee",
        sa.Column(
            "mother_grandfather_name",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
    )
    op.add_column(
        "employee", sa.Column("apprenticeship_from_date", sa.Date(), nullable=False)
    )
    op.add_column(
        "employee", sa.Column("apprenticeship_to_date", sa.Date(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee", "apprenticeship_to_date")
    op.drop_column("employee", "apprenticeship_from_date")
    op.drop_column("employee", "mother_grandfather_name")
    op.drop_column("employee", "origin_of_birth")
    # ### end Alembic commands ###
